import requests
from send_email import send_email

topic = "tesla"
# Got from NewsAPI website
api_key = "effb4aae6a1048a69f14a8bacff24504"

# This url was generated by NewsAPI website
url = f"https://newsapi.org/v2/everything?q={topic}&from=2024-05-05&sortBy=" \
      "publishedAt&apiKey=effb4aae6a1048a69f14a8bacff24504&language=en"

# Made a request
request = requests.get(url)

# The method json generates a readable dictionary format
content = request.json()

message = ""
# Content is a dict of 3 items, where the item "articles" is the key for a list
# of 100 dicts, each one with 8 items. This can be seen by debugger
for article in content["articles"][:20]:
    if article["title"] and article["description"] is not None:
        message = message + article["title"] + "\n" \
                + article["description"] \
                + "\n" + article["url"] + 2*"\n"

message = "Subject: Today's news" + "\n" + message
# This string method removes the non ASCII characters
message = message.encode("utf-8")
send_email(message)
